version: '3.3'

services:
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: blsglobal_root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: bls
      HTTPS: "off"
    depends_on:
      - db
    volumes:
      - ./volumes/wordpress:/var/www/html

  db:
    build: ./docker/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: bls
      MYSQL_USER: blsglobal_root
      MYSQL_PASSWORD: root
    volumes:
      - ./volumes/mysql:/var/lib/mysql
      # - ./volumes/dump:/docker-entrypoint-initdb.d
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on:
      - db
    links:
      - db
    ports:
      - 8183:80
    environment:
      PMA_HOST: db
      MYSQL_USER: blsglobal_root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: somewordpress
      UPLOAD_LIMIT: 204800m
    volumes:
      - ./volumes/phpmyadmin:/usr/local/etc/php/
      - ./volumes/phpmyadmin:/etc/phpmyadmin/config.user.inc.php